model_list:
  - model_name: gpt-5-mini
    litellm_params:
      model: openai/gpt-5-mini
      api_key: os.environ/OPENAI_API_KEY
      reasoning_effort: low
      verbosity: high

litellm_settings:
  drop_params: True
  num_retries: 5
  request_timeout: 600
  telemetry: False